### ISSUE TITLE
Enhance the generated CSS

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#136]
**Describe alternatives you've considered**
The current generated CSS classes may contain duplicate rules. We should be able to apply a some CSS deduplication before generating the style file.

**Comment by Shikanime** [comment]
@manekinekko  By default the layer.css is an object. How can it have duplicate key ? 🤔

**Comment by manekinekko** [comment]
I was referring to the CSS codegen. We need to run an optimization phase post-codegen (or pre?) to avoid duplicate css rules.

**Comment by manekinekko** [comment]
Leaving this doc here as a ref: 

[*Eliminating Code Duplication in Cascading Style Sheets by Davood Mazinanian. A Thesis In the Department of Computer Science and Software Engineering*](https://users.encs.concordia.ca/~nikolaos/theses/Davood_Mazinanian.pdf)

**Comment by Jefiozie** [comment]
Leaving this for a reference: [link to experimental repo](https://github.com/Jefiozie/xlayers/tree/feature/ExtendingParser)

**Comment by Jefiozie** [comment]
To give a small update on this topic. At the moment I'm removing all duplicate CS S declarations from the stylesheet.

`Original`
```css
.xly_2ka8 {
  display: block;
  position: absolute;
  left: 0px;
  top: 0px;
  width: 344px;
  height: 208px;
  visibility: visible;
}

.xly_jop1 {
  border-radius: 3px;
  display: block;
  position: absolute;
  left: 0px;
  top: 0px;
  width: 344px;
  height: 208px;
  visibility: visible;
  box-shadow: 0px 2px 2px 0px rgba(0, 0, 0, 0.24),
    0px 0px 2px 0px rgba(0, 0, 0, 0.12);
  background-color: rgba(250, 250, 250, 1);
  opacity: 1;
}
```

`Undoubled` 

```css
.xly_cocu {
  position: absolute;
  left: 0px;
  top: 0px;
  width: 344px;
  height: 208px;
  visibility: visible;
}

.xly_doh1 {
  border-radius: 3px;
  box-shadow: 0px 2px 2px 0px rgba(0, 0, 0, 0.24),
    0px 0px 2px 0px rgba(0, 0, 0, 0.12);
  background-color: rgba(250, 250, 250, 1);
  opacity: 1;
}
```


Next to step is to extract the undoubled declarations and add the references to the original css classes so that both have the needed declarations

`example (ish)`

```css

.xly_cocu {
  position: absolute;
  left: 0px;
  top: 0px;
  width: 344px;
  height: 208px;
  visibility: visible;
}

.xly_doh1 {
  border-radius: 3px;
  box-shadow: 0px 2px 2px 0px rgba(0, 0, 0, 0.24),
    0px 0px 2px 0px rgba(0, 0, 0, 0.12);
  background-color: rgba(250, 250, 250, 1);
  opacity: 1;
}

.xly_doh1, .xly_aew3 {
  left: 0px;
  top: 0px;
  width: 344px;
  height: 208px;
}

```
